import { launch, shot, goto, txt, obs, adv } from './rev-common.js';
import { startRun, drive } from './rev-player.js';
const tier = process.argv[2] ?? '0'; const seed = process.argv[3] ?? '1';
const h = await launch(); const { page } = h;
await goto(page, `#/cockpit/drill/D16/${tier}/${seed}`); await page.waitForTimeout(500);
console.log('PREREAD:', (await txt(page, '#preread')).replace(/\n/g, ' | '));
await shot(page, `d16-t${tier}-preread-1366`);
await page.keyboard.press('Escape');
const o = await obs(page); console.log('start', o.startTime, JSON.stringify(o.book.map((b: any) => `${b.n}: ${b.text}${b.restartTime !== undefined ? ' [restartTime ' + b.restartTime + ']' : ''}`)));
console.log('book rows rendered:\n' + (await page.locator('#book .row').evaluateAll(r => r.map(x => (x as HTMLElement).innerText.replace(/\n/g, ' ').slice(0, 140)))).join('\n'));
await startRun(page, { departEarly: 5 });
const opts: any = { name: 'D16', verbose: true };
await drive(page, opts, 'o.driver.waitingForGo && o.stoppedAtLine && o.tod > 28800 + 60');
await page.waitForTimeout(150); await shot(page, `d16-t${tier}-restart-hold-1366`);
const o2 = await obs(page); console.log('HOLD state: stopped', o2.stoppedAtLine, 'cur', o2.currentLine, o2.driver.state, 'tod', o2.tod.toFixed(1), 'start chip:', (await txt(page, '#tod')));
console.log('perfcard:', (await txt(page, '#perfcard')).replace(/\n/g, ' | '));
console.log('stopped row:', (await page.locator('#book .row.stopped').innerText().catch(() => 'NONE')).replace(/\n/g, ' | '));
console.log('road pace text region (canvas) -> aids', JSON.stringify(o2.aids));
console.log('dad:', (await txt(page, '#driverlog')).replace(/\n/g, ' | '));
await drive(page, opts);
await page.waitForSelector('#debrief', { timeout: 30000 }); await page.waitForSelector('#counterfactuals .cf-row', { timeout: 15000 }).catch(() => {});
await page.waitForTimeout(300);
const t = await txt(page, '#debrief'); console.log(t.slice(0, 3200));
await shot(page, `d16-t${tier}-debrief`, true);
console.log('errors', h.errors);
await h.save(); await h.browser.close();
