import { launch, shot, goto, txt, adv, obs } from './rev-common.js';
import { startRun, drive } from './rev-player.js';
const h = await launch(); const { page } = h;
await goto(page, '#/');
await page.click('#starthere'); await page.waitForTimeout(500);
console.log('hash', await page.evaluate(() => location.hash));
console.log('PREREAD:\n', await txt(page, '#preread'));
await page.keyboard.press('Escape');
const info = await obs(page); console.log(info.book.map((b: any) => `${b.n}: ${b.text}`).join('\n'));
async function runTo(opts: any, tag: string, startOpts: any = {}) {
  await startRun(page, startOpts);
  await drive(page, { name: 'D03', ...opts, verbose: true }, 'o.stoppedAtLine !== null && o.tod > 28800+20');
  await page.waitForTimeout(150); await shot(page, `d03-${tag}-at-stop`);
  const o = await obs(page);
  console.log(`[${tag}] AT FIRST STOP: stoppedAtLine=${o.stoppedAtLine} currentLine=${o.currentLine}`);
  console.log('  perfcard:', (await txt(page, '#perfcard')).replace(/\n/g, ' | '));
  console.log('  stopped row:', (await page.locator('#book .row.stopped').innerText().catch(() => 'NONE')).replace(/\n/g, ' | '));
  console.log('  pace:', await page.evaluate(() => (document.querySelector('.lapboard')?.innerText ?? '').slice(0, 300)).then(t => t.replace(/\n/g, ' | ')));
  console.log('  dad:', (await txt(page, '#driverlog')).replace(/\n/g, ' | '));
  const log = await drive(page, { name: 'D03', ...opts, verbose: true });
  console.log(tag, JSON.stringify({ keys: log.keys, sim: log.wall1x.toFixed(0), a4: log.wallAdaptive4x.toFixed(0), wait: log.waitingSeconds.toFixed(0) }));
  await page.waitForSelector('#debrief', { timeout: 20000 }); await page.waitForSelector('#counterfactuals .cf-row', { timeout: 15000 }).catch(() => {});
  await page.waitForTimeout(300);
  console.log((await txt(page, '#debrief')).slice(0, 4500));
  await shot(page, `d03-${tag}-debrief`); await shot(page, `d03-${tag}-debrief-full`, true);
}
await runTo({ dwellFull: true, goNoise: 0.8 }, 'run1-naive');
console.log('========== RETRY (button) ==========');
await page.getByText('Retry this run').first().click(); await page.waitForTimeout(500);
console.log('hash', await page.evaluate(() => location.hash), 'history len', await page.evaluate(() => history.length));
await page.keyboard.press('Escape');
console.log('scale chip after retry:', await txt(page, '#scale'));
await runTo({ bezel: true }, 'run2-card', { noWatch: true });
await goto(page, '#/');
console.log('home D03:', (await txt(page, '.card[data-drill="D03"]')).replace(/\n/g, ' | '));
console.log('lastruns:', await txt(page, '#lastruns'));
console.log('startpath:', await page.locator('#starthere-panel li').evaluateAll(l => l.map(x => x.className + ':' + x.textContent)));
console.log('errors', h.errors, 'dialogs', h.dialogs);
await h.save(); await h.browser.close();
