import { launch, shot, goto, txt, obs } from './rev-common.js';
import { startRun, drive } from './rev-player.js';
const h = await launch({ width: 1920, height: 1080 }); const { page } = h;
// legal player reads the Ford table off the Reference page (paper tables are legal)
await goto(page, '#/reference');
const table = await page.evaluate(() => { const d = document.querySelector('#answer-sheet')!; const t = d.querySelector('table')!; const heads = [...t.querySelectorAll('thead th')].slice(1).map(x => Number(x.textContent)); const loss = [...t.querySelectorAll('tbody tr')].map(r => [...r.querySelectorAll('td')].slice(1).map(x => Number(x.textContent))); return { speeds: heads, loss, turnExtra: 1.5 }; });
console.log('reference table speeds', table.speeds.join(','), 'rows', table.loss.length, 'answer sheet open:', await page.evaluate(() => document.querySelector('#answer-sheet')!.hasAttribute('open')));
await shot(page, 'reference-1920');
await goto(page, '#/');
console.log('home D03 pips:', (await txt(page, '.card[data-drill="D03"] .pips')).replace(/\n/g, ' '));
await goto(page, '#/cockpit/drill/D03/2/1'); await page.waitForTimeout(500);
console.log('PREREAD (gold):', (await txt(page, '#preread')).slice(0, 600).replace(/\n/g, ' | '));
await shot(page, 'd03gold-preread-1920');
await page.keyboard.press('Escape');
console.log('drawer bar:', await page.locator('.drawer .bar .muted').last().innerText());
console.log('tod chip visible?', await page.locator('#tod').isVisible(), '| captions:', JSON.stringify(await page.locator('.instruments .caption').allInnerTexts()));
await startRun(page, { noWatch: true });
await drive(page, { name: 'D03', bezel: true, table, verbose: true }, 'o.stoppedAtLine !== null && o.tod > 28800+20');
await page.waitForTimeout(150); await shot(page, 'd03gold-at-stop-1920');
const o = await obs(page);
console.log('AT FIRST STOP: stoppedAtLine', o.stoppedAtLine, 'cur', o.currentLine, 'rung aids', JSON.stringify(o.aids));
console.log('perfcard:', (await txt(page, '#perfcard')).replace(/\n/g, ' | '));
console.log('book rows text:', (await page.locator('#book .row.stopped').innerText().catch(() => 'NONE')).replace(/\n/g, ' | '));
console.log('captions:', JSON.stringify(await page.locator('.instruments .caption').allInnerTexts()));
console.log('hud:', (await txt(page, '.hud')).replace(/\n/g, ' | '));
const log = await drive(page, { name: 'D03', bezel: true, table, verbose: true });
console.log('gold', JSON.stringify({ keys: log.keys, sim: log.wall1x.toFixed(0) }));
await page.waitForSelector('#debrief', { timeout: 30000 }); await page.waitForSelector('#counterfactuals .cf-row', { timeout: 15000 }).catch(() => {});
await page.waitForTimeout(300);
const t = await txt(page, '#debrief'); console.log(t.slice(0, 2600));
await shot(page, 'd03gold-debrief-1920', true);
console.log('bias tail:', t.slice(t.indexOf('MANEUVER')).slice(0, 900));
await goto(page, '#/');
console.log('home D03:', (await txt(page, '.card[data-drill="D03"]')).replace(/\n/g, ' | '));
console.log('lastruns', await txt(page, '#lastruns'));
console.log('errors', h.errors);
await h.save(); await h.browser.close();
